version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      testing:
        patterns:
          - "@playwright/*"
          - "vitest"
          - "@vitest/*"
          - "@testing-library/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "@epic-web/config-eslint"
          - "typescript-eslint"
      remix:
        patterns:
          - "@remix-run/*"
      aws:
        patterns:
          - "@aws-sdk/*"
      conform:
        patterns:
          - "@conform-to/*"
      dnd:
        patterns:
          - "@dnd-kit/*"
