-- AlterTable
ALTER TABLE "Track" ADD COLUMN "albumArtist" TEXT;
ALTER TABLE "Track" ADD COLUMN "bpm" INTEGER;
ALTER TABLE "Track" ADD COLUMN "genre" TEXT;
ALTER TABLE "Track" ADD COLUMN "isrc" TEXT;
ALTER TABLE "Track" ADD COLUMN "label" TEXT;
ALTER TABLE "Track" ADD COLUMN "lyrics" TEXT;
ALTER TABLE "Track" ADD COLUMN "originalDate" DATETIME;
ALTER TABLE "Track" ADD COLUMN "originalYear" INTEGER;
ALTER TABLE "Track" ADD COLUMN "totalDiscs" INTEGER;
ALTER TABLE "Track" ADD COLUMN "totalTracks" INTEGER;
ALTER TABLE "Track" ADD COLUMN "trackNumber" INTEGER;
ALTER TABLE "Track" ADD COLUMN "year" INTEGER;
