#!/usr/bin/env python3
"""Generate dummy audio fixtures for E2E tests.

Creates 2-second silent MP3 files that the Tigris mock serves at runtime.
The audio is long enough for Playwright tests to detect play/pause state transitions.
"""
import os
import shutil

# Reference MP3: 2-second silent stereo MP3 at 44100Hz, generated by ffmpeg:
#   ffmpeg -f lavfi -i anullsrc=r=44100:cl=stereo -t 2 -q:a 9 -acodec libmp3lame <output>
REF_MP3 = os.path.join(os.path.dirname(__file__), 'silent-2s-reference.mp3')
OUT_DIR = os.path.join(os.path.dirname(__file__), 'uploaded', 'audio')

os.makedirs(OUT_DIR, exist_ok=True)

test_keys = [
    'test-download.mp3',
    'test-keyboard.mp3',
    'test-loop.mp3',
    'test-mobile.mp3',
    'test-mutekey.mp3',
    'test-nowplaying.mp3',
    'test-playlist.mp3',
    'test-seek.mp3',
    'test-shuffle.mp3',
    'test-sleep.mp3',
    'test-transport.mp3',
    'test-volume.mp3',
]

for key in test_keys:
    filepath = os.path.join(OUT_DIR, key)
    shutil.copy2(REF_MP3, filepath)
    size = os.path.getsize(filepath)
    print(f'Created {filepath} ({size} bytes)')

print('Done')
